Feature/add contextno repo
first-exp/contextno-bot pull request #2
Opened 2024-05-28 14:49 UTC by PolinaLack

2024-05-28 15:33 UTC, EgorKalugin requested changes

2024-05-28 15:33 UTC, EgorKalugin commented on .gitignore
> +comments.py
а зачем этот файл в gitignore ?

2024-05-28 15:33 UTC, EgorKalugin commented on models/contextno.py
> +    chat_id: str = None  # type: ignore
А разве может chat_id быть None? Давай уберем None и тайп игнор

2024-05-28 15:33 UTC, EgorKalugin commented on repository/contextno.py
> +    def __init__(self, http_session):
добавь тут тип для http_session

2024-05-28 15:33 UTC, EgorKalugin commented on repository/contextno.py
> +    async def start_game(self) -> ContextnoSession:
давай переименуем **start_game** на **get_challenge_id**

2024-05-28 15:33 UTC, EgorKalugin commented on repository/contextno.py
> +            resp: ClientResponse = await self.http_session.get(
тут аннотация **: ClientResponse** лишняя

2024-05-28 15:33 UTC, EgorKalugin commented on repository/contextno.py
> +            game_sess = ContextnoSession(challenge_id=new_cont_sess.id)
Давай  **challenge_id** возвращать сразу, сервис сам обернет в ContextnoSession.

2024-05-28 15:33 UTC, EgorKalugin commented on repository/contextno.py
> +            game_sess = ContextnoSession(challenge_id=new_cont_sess.id)
Ну и модель ContextnoSessionIn как-будто не нужна

2024-05-28 15:33 UTC, EgorKalugin commented on repository/contextno.py
> +            game_sess = ContextnoSession(challenge_id=new_cont_sess.id)
```python
data = await resp.json()
return int(data["id"])
```

2024-05-28 15:33 UTC, EgorKalugin commented on repository/contextno.py
> +                print(f"Error starting session: {e}")
Давай try/except блок уберем во всех методах. Мы все равно никак ошибку не обрабатываем в них

2024-05-28 15:57 UTC, PolinaLack commented on .gitignore
> +comments.py
я туда скидываю всё, что на данный момент не нужно
чтобы потом удалить

2024-05-28 15:58 UTC, PolinaLack commented on models/contextno.py
> +    chat_id: str = None  # type: ignore
мне для тестов было нужно
проглядела, сейчас поправлю

2024-05-28 16:01 UTC, PolinaLack commented on repository/contextno.py
> +    def __init__(self, http_session):
+

2024-05-28 16:02 UTC, PolinaLack commented on repository/contextno.py
> +    async def start_game(self) -> ContextnoSession:
\+

2024-05-28 16:11 UTC, PolinaLack commented on repository/contextno.py
> +            game_sess = ContextnoSession(challenge_id=new_cont_sess.id)
\+

2024-05-28 16:13 UTC, EgorKalugin commented on .gitignore
> +comments.py
давай уберем, можешь его в .vscode перенести и папку .vscode в гитигнор добавить

2024-05-28 16:26 UTC, PolinaLack commented on repository/contextno.py
> +                print(f"Error starting session: {e}")
\+

2024-05-28 18:03 UTC, PolinaLack commented on repository/contextno.py
> +            game_sess = ContextnoSession(challenge_id=new_cont_sess.id)
единственное в data["id"] не только цифры, но и буквы

2024-05-29 07:09 UTC, PolinaLack commented on .gitignore
> +comments.py
\+

2024-05-29 07:10 UTC, EgorKalugin approved these changes

2024-05-29 07:11 UTC, merged