Feature/add docker
first-exp/contextno-bot pull request #3
Opened 2024-05-30 20:13 UTC by PolinaLack

2024-06-01 08:50 UTC, EgorKalugin requested changes

2024-06-01 08:50 UTC, EgorKalugin commented on .gitignore
> +config.py
а зачем этот файл в гитигноре?

2024-06-01 08:50 UTC, EgorKalugin commented on .gitignore
> +config.py
давай сделаем его как в примере https://fastapi.tiangolo.com/ru/advanced/settings/#read-settings-from-env
Должен получится класс сетингов для бота с двумя аттрибутами: redis_url и tg_token.
Сами секреты лежат в файле .env, который мы добавим в гитигнор и не будем пушить

2024-06-01 15:10 UTC, PolinaLack commented on .gitignore
> +config.py
+

2024-06-04 14:51 UTC, EgorKalugin approved these changes

2024-06-04 14:52 UTC, merged